language: php
php:
    - '5.6'
    - '7.0'
    - '7.1'

notifications:
    email: false

before_script: composer install

script:
    - php vendor/bin/phpunit

after_script:
    - php vendor/bin/coveralls -v
